### ISSUE TITLE
Upgrade to Raven 4.0

### ISSUE THREAD

**Issue by maqduni** [maqduni/AspNetCore.Identity.RavenDb#11]
Create an RC for RavenDB-4.0.0-nightly-20171031-0500

**Comment by pekkah** [comment]
Unique Constraints is not supported with RavenDb 4. Details here https://ayende.com/blog/180066/unique-constraints-didnt-make-the-cut-for-ravendb-4-0

**Comment by maqduni** [comment]
I appreciate that you shared the link. I asked about it a while ago in a google group but they didn't respond. I'll see what I can do about it.

**Comment by maqduni** [comment]
Please let me know if you have any ideas.

**Comment by maqduni** [comment]
His followup article on unique constraints https://ayende.com/blog/180067/ravendb-4-0-interlocked-distributed-operations.

**Comment by maqduni** [comment]
Persistence store for RavenDB v4.0 is ready. Will upload the RC packages to NuGet as soon as I can. Meanwhile you can test it by downloading the main branch and trying the sample web application.

**Comment by maqduni** [comment]
Deployed RC package to NuGet https://www.nuget.org/packages/Maqduni.AspNetCore.Identity.RavenDb/2.0.0-rc-nightly-20171126-0501

**Comment by maqduni** [comment]
Released version 2.0.1 for RavenDB v4.0.1
