### ISSUE TITLE
Upgrade to .NET Core 2.0

### ISSUE THREAD

**Issue by maqduni** [maqduni/AspNetCore.Identity.RavenDb#12]

**Comment by tobiaszuercher** [comment]
we'd love to see this! our only dependency that is not .NET Core 2.0 compatible is this lib.

**Comment by maqduni** [comment]
Upgraded to .NET Core 2.0. Please download and test the latest version from NuGet. Let me know if you have any issues or questions.

**Comment by maqduni** [comment]
Let me know if you have any issues or questions otherwise I'll close the issue.

**Comment by tobiaszuercher** [comment]
thank you @maqduni 
currently i'm on vacation :)

**Comment by maqduni** [comment]
No worries, I'll close the issue then. Feel free to reopen it or file a new one in case of finding errors.
