### ISSUE TITLE
Claims cannot be removed from role

### ISSUE THREAD

**Issue by michaelschnyder** [maqduni/AspNetCore.Identity.RavenDb#13]
There is an issue regardingthe method `RemoveClaimAsync` the following code fails because the list that is enummerated will change during execution. 

```c#
var claims = role.Claims.Where(c => c.ClaimValue == claim.Value).
foreach (var c in claims)
{
    role.Claims.Remove(c);
}
```
Throws
**System.InvalidOperationException**: 'Collection was modified; enumeration operation may not execute.'

I'll try to provide a PR to resolve this

**Comment by maqduni** [comment]
I requested two little changes in the unit tests. Besides that the fix looks great! Thank you very much for your contribution, I much appreciate it!

As soon as you make the changes I'll publish a new version to NuGet.
