### ISSUE TITLE
ravendb client 4.2.0 compatibility

### ISSUE THREAD

**Issue by sadeghhp** [maqduni/AspNetCore.Identity.RavenDb#19]
Could you please make this compatible with ravendb client 4.2.0 ?

**Comment by maqduni** [comment]
Hey Sadegh, I'll try update it until the end of this week.

**Comment by maqduni** [comment]
I uploaded new version to NuGet, https://www.nuget.org/packages/Maqduni.AspNetCore.Identity.RavenDb/4.2.0. Let me know if you have any questions or issues with it.
