### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'AddRavenDbAsyncSession' and no extension method 'AddRavenDbAsyncSession' accepting a first argument of type 'IServiceCollection' could be found 

### ISSUE THREAD

**Issue by krime81** [maqduni/AspNetCore.Identity.RavenDb#4]
in a new asp.net core web application (.net framework)
i get this error.

**Comment by maqduni** [comment]
What version of the package are you using? Have you tried the latest, 1.3.25?

**Comment by krime81** [comment]
1.3.25 (targeting 4.6.1)

looking at your code, i cant see whats wrong either,
the extension methods look just fine

**Comment by maqduni** [comment]
Just created an Asp.Net Core Web Application targeting 4.6.1, all namespaces are available.

Do you have all necessary namespaces imported?
```
using Maqduni.AspNetCore.Identity.RavenDb;
using Maqduni.Extensions.DependencyInjection;
```

Are there any errors in the References folder of your project?

**Comment by krime81** [comment]
:$ forgot to import the namespaces. silly me. thanks A LOT

**Comment by maqduni** [comment]
I'm glad it got resolved, was starting to get worried :) Let me know if you have any further questions. I appreciate your input a lot!
