### ISSUE TITLE
TypeLoadException: Inheritance security rules violated

### ISSUE THREAD

**Issue by krime81** [maqduni/AspNetCore.Identity.RavenDb#6]
by type: 'System.Net.Http.WebRequestHandler'. Derived types must either match the security accessibility of the base type or be less accessible.

I get this on ALL ravendb operations (query/store,...)

any idea what this might be ?
(dont worry, think its not directly related to this project, just hoping you mightve encountered this before)

**Comment by maqduni** [comment]
Have you seen this issue, [https://github.com/dotnet/corefx/issues/11100](https://github.com/dotnet/corefx/issues/11100)?

There is also a relevant stackoverflow question, take a look, [http://stackoverflow.com/questions/38626316/inheritance-sec-rules-violated-by-type-system-net-http-webrequesthandler](http://stackoverflow.com/questions/38626316/inheritance-sec-rules-violated-by-type-system-net-http-webrequesthandler).

**Comment by krime81** [comment]
wow. i skipped it, cause i dont use the package system.net.http directly.
now i installed it, poof. it works.
this is beyond me....

**Comment by maqduni** [comment]
:) Awesome!
