### ISSUE TITLE
FindByEmailAsync is always null

### ISSUE THREAD

**Issue by codescribler** [maqduni/AspNetCore.Identity.RavenDb#9]
When using the UserManager I can create users but I can't retrieve them. Any of the FindBy... return null.

**Comment by maqduni** [comment]
I have a feeling you don't have Unique Constraints bundle installed in your Raven server. Could you verify that it's properly set up and see if that helps?

I also recommend you download the source code and play around with the unit tests if you have a feeling you are doing something wrong. That'll give you a better understanding of the implementation of the library.

**Comment by maqduni** [comment]
Keep in mind, you'll have to recreate the user, because unique constraint objects are created on user creation. Or manually delete the user from the database and recreate him through the ui.

**Comment by maqduni** [comment]
Closing the issue due to lack of further feedback from the user.
